services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - mssql-network
    environment:
      - MSSQL_PID=developer
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongPassword99!
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    deploy:
      resources:
        limits:
          memory: 4g

networks:
  mssql-network:
    driver: bridge